"""
brain/plan_generator.py — Multi-step action plan generation.

Produces an ActionPlan (sequence of ActionRecommendations) for content
types that benefit from more than one follow-up action.  The first step
is pre-generated by proactive.py; subsequent steps are generated on demand
when the user approves the previous step.
"""

from brain.action_schema import ActionPlan, ActionRecommendation, classify_risk, default_target


# ── Plan templates ────────────────────────────────────────────────────────────
# (action_key, display_label) ordered by natural execution sequence.

_PLANS: dict[str, list[tuple[str, str]]] = {
    "email_thread": [
        ("reply",      "Draft reply"),
        ("follow_up",  "Schedule follow-up"),
    ],
    "form": [
        ("form_fill",  "Fill fields"),
        ("submit",     "Submit form"),
    ],
    "approval_item": [
        ("analyze_queue",   "Analyze risks"),
        ("flag_risks",      "Flag issues"),
        ("escalation_list", "Escalate if needed"),
    ],
}


# ── Builder ───────────────────────────────────────────────────────────────────

def _make_step(
    action_key:   str,
    label:        str,
    content_type: str,
    app_name:     str = "",
) -> ActionRecommendation:
    from brain.priority_queue import _generate_reasoning
    risk = classify_risk(action_key)
    return ActionRecommendation(
        action_key   = action_key,
        label        = label,
        confidence   = 0.80,
        priority     = 0.70,
        risk_level   = risk,
        target       = default_target(risk),
        context_type = content_type,
        reasoning    = _generate_reasoning(action_key, content_type, 0.80, None, app_name),
    )


def generate_plan(
    content_type: str,
    text: str = "",
    signals=None,
    app_name: str = "",
) -> "ActionPlan | None":
    """
    Return an ActionPlan for this content_type, or None if no plan applies.
    Steps are ActionRecommendations with action_key, label, and reasoning set;
    AI-generated content for each step is stored separately in the proactive cache.
    """
    rules = _PLANS.get(content_type)
    if not rules:
        return None

    steps = [_make_step(ak, lbl, content_type, app_name) for ak, lbl in rules]
    return ActionPlan(steps=steps, current_step=0, status="active")
